name: Create preview environment
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build:
    timeout-minutes: 15
    concurrency: preevy-${{ github.event.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          npx preevy up --enable-plugin "@preevy/plugin-github" --profile "s3://preevy-455217234700-default-s3?region=us-east-1"