name: Teardown Preevy environment
on:
  pull_request:
    types:
      - closed
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: livecycle/preevy-down-action@v1.3.0
        id: preevy
        with:
          profile-url: "s3://preevy-455217234700-default-s3?region=us-east-1"
