name: Teardown Preevy environment
on:
  pull_request:
    types:
      - closed
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npx preevy down \
            --github-token=${{ github.token }} \
            --github-pull-request=${{ github.event.number }} \
            --github-repo=${{ github.repository }} \
            --profile "s3://preevy-455217234700-default-s3?region=us-east-1"
